name: BSides Montreal 2023

on: workflow_dispatch

jobs:
  hello-world: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Bsides Montreal"
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP ZAP
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
